export enum ActionType {
  CATEGORIES = 'CATEGORIES',
  FOOD_SEARCH = 'FOOD_SEARCH',
  OFFER_SEARCH = 'OFFER_SEARCH',
  TOP_RESTAURANTS = 'TOP_RESTAURANTS',
  FOODS_30MIN = 'FOODS_30MIN',
  SHOP_ERROR = 'SHOP_ERROR'
}
