export enum ActionType {
  ADD_TO_CART = 'ADD_TO_CART',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  UPDATE_LOCATION = 'UPDATE_LOCATION',
  USER_ERROR = 'USER_ERROR',
}
