export enum Routes {
  Account = 'Account',
  BottomTab = 'BottomTab',
  Cart = 'Cart',
  CartNavigator = 'CartNavigator',
  FoodDetails = 'FoodDetails',
  Home = 'Home',
  HomeNavigator = 'HomeNavigator',
  Login = 'Login',
  Offers = 'Offers',
  OrderDetails = 'OrderDetails',
  Orders = 'Orders',
  Restaurant = 'Restaurant',
  Search = 'Search',
  Welcome = 'Welcome',
}
